language: csharp
sudo: required
dist: trusty

dotnet: 7.0.101 
mono:
  - latest # => "stable release"
os:
  - linux

addons:
  apt:
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

script:
  - dotnet restore
  - dotnet test tests/Tests

branches:
  only:
  - master
