init:
  - git config --global core.autocrlf input

before_build:
  - ps: >-
      $buildId = $env:APPVEYOR_BUILD_NUMBER.PadLeft(5, '0');
      $versionSuffixPR = "-PR$($env:APPVEYOR_PULL_REQUEST_NUMBER)-$buildId";
      $branchName = "$env:APPVEYOR_REPO_BRANCH".Replace("_","");
      $versionSuffixBRANCH = "-$branchName-$buildId";
      $env:VersionSuffix = if ("$env:APPVEYOR_REPO_TAG" -eq "true") { "" } else { if ("$env:APPVEYOR_PULL_REQUEST_NUMBER") { $versionSuffixPR } else { $versionSuffixBRANCH } };
build_script:
  - cmd: echo vs %VersionSuffix%"
  - cmd: dotnet restore
  - cmd: dotnet test tests\Tests
  - cmd: dotnet pack src\FSharpPlus.AspNetCore -o ../../dist -c Release
  - cmd: dotnet pack src\FSharpPlus.AspNetCore.Suave -o ../../dist -c Release
test: "off"
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
  - path: dist
    name: dist
branches:
  only:
  - master
