init:
  - git config --global core.autocrlf input
build_script:
  - cmd: dotnet restore
  - cmd: dotnet test tests\Tests
  - cmd: dotnet pack src\FSharpPlus.AspNetCore -o ../../dist -c Release
  - cmd: dotnet pack src\FSharpPlus.AspNetCore.Suave -o ../../dist -c Release
test: "off"
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
  - path: dist
    name: dist
branches:
  only:
  - master
